# Generated by Django 3.1.3 on 2021-07-08 04:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import transactions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True)),
                ('updated_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'ArticleMaster',
                'verbose_name_plural': 'ArticleMaster',
            },
        ),
        migrations.CreateModel(
            name='BranchMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True)),
                ('updated_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'BranchMaster',
                'verbose_name_plural': 'BranchMasters',
            },
        ),
        migrations.CreateModel(
            name='ColorMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True)),
                ('updated_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'ColorMaster',
                'verbose_name_plural': 'ColorMaster',
            },
        ),
        migrations.CreateModel(
            name='CompanyLedgerMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True)),
                ('updated_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'CompanyLedgerMaster',
                'verbose_name_plural': 'CompanyLedgerMasters',
            },
        ),
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True)),
                ('updated_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'DepartmentMaster',
                'verbose_name_plural': 'DepartmentMasters',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_quantity', models.FloatField(null=True)),
                ('net_quantity', models.FloatField(null=True)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METER', 'METER')], max_length=50, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.articlemaster')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.colormaster')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.companyledgermaster')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_on_date', models.DateField(blank=True, null=True)),
                ('quanitty', models.FloatField(null=True)),
                ('rate_per_unit', models.IntegerField(null=True)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('METER', 'METER')], max_length=50, null=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.articlemaster')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.colormaster')),
                ('inventory', models.ManyToManyField(blank=True, related_name='inventory_line', to='transactions.Inventory')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_number', models.CharField(db_index=True, default=transactions.models.generate_transaction_id, editable=False, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('CLOSE', 'CLOSE')], max_length=50, null=True)),
                ('remark', models.TextField(null=True)),
                ('created_date', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True)),
                ('updated_date', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.branchmaster')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.companyledgermaster')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transactions.departmentmaster')),
                ('tran_line', models.ManyToManyField(blank=True, related_name='transaction_time_line', to='transactions.TransactionLine')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
