# Generated by Django 3.1.3 on 2021-07-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionline',
            old_name='quanitty',
            new_name='quanitity',
        ),
    ]
